### ISSUE TITLE
How to set properties non-executor-specific?

### ISSUE THREAD

**Issue by gbonnefille** [alekc/gitlab-runner-operator#15]
In a classical gitlab-runner deployment, I will set some properties like "environment" (for example in order to declare HTTP proxy). This property is not specific to the Kubernetes executor. So, I cannot declare it in the executor_config.

Is there any solution for that?

**Comment by alekc** [comment]
Sorry, I am not sure I am understanding your question. Are looking for a way to set up env variable on worker pods?

**Comment by gbonnefille** [comment]
Sorry for not being clear.
I'm looking for a way to configure the `environment` property of the https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runners-section

**Comment by alekc** [comment]
Sorry, i am on holiday ATM, should be able to get back to you this weekend

**Comment by alekc** [comment]
Right. So, the good news is that it can be easily supported since the structure used for config generation already has it in place (https://github.com/alekc/gitlab-runner-operator/blob/01d060ad54fbf272250ff962c450404615102027/config/config.go#L39) but there is no setting &  link present in CRD definition. 

May I ask what's the use case for having this setting separately and not using Gitlab variable/putting it inside .gitlab-ci.yaml? @gbonnefille

**Comment by gbonnefille** [comment]
> May I ask what's the use case for having this setting separately and not using Gitlab variable/putting it inside .gitlab-ci.yaml? 

I need to define the HTTP proxy var env in order to pass corporate proxy. I don't want to set these settings in the different `.gitlab-ci.yaml` because:
- it is a matter of the runner, not the project (I can add a runner without the constraint of using proxy)
- I don't want to repeat myself in ALL the projects using this runner.

**Comment by alekc** [comment]
Make sense. I will add a support for it shortly

**Comment by alekc** [comment]
@gbonnefille  try the 1.5.0 version of the helm chart, it has a support for the environment. 
In your case it should be something like 
```yaml
apiVersion: gitlab.k8s.alekc.dev/v1beta1
kind: Runner
metadata:
  name: runner-sample
spec:
  environment:
    - "http_proxy=https://xxxxx:3128"
  concurrent: 1
  log_level: info
  gitlab_instance_url: https://gitlab.com
  registration_config: {}   
```

Edit: there is a CRD update involved, so depending on your delivery method you might need to run kubectl apply on crd file first.
